services:
  server:
    command: ["emailproxy", "--no-gui", "--external-auth", "--config-file", "/app/emailproxy.config"]
    build: .
    ports:
      - "2587:2587"
    stdin_open: true
    tty: true
    volumes:
      - ./emailproxy.config:/app/emailproxy.config
